Music/urls.py
from django.conf import settings
from django.conf.urls import static, url
from django.urls import path, include
from . import views

app_name = "Music"

urlpatterns = [
    path("", views.index, name="index"),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('playlist/', views.playlist_view, name='playlist'),
    path('recommendedsong/', views.recommended_song, name='recommendedsong'),
    path(r'^singleplaylist/(?P<id>[0-9]+)$',
         views.playlist_detail, name='singleplaylist'),
     path('logout/', views.logout, name='logout')



]

MusicFinaltesting1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Music.urls")),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Music/models.py
from django.db.models.deletion import CASCADE
from djongo import models
from django import forms


class User(models.Model):
    OPTIONS = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )
    Firstname = models.CharField(max_length=255)
    LastName = models.CharField(max_length=255)
    Username = models.CharField(max_length=255)
    Email = models.EmailField()
    Password = models.CharField(max_length=255)
    Gender = models.CharField(default='', max_length=255, choices=OPTIONS)
    Age = models.IntegerField()


class Song(models.Model):
    OPTIONS = (
        ('HipHop', 'HipHop'),
        ('Jazz', 'Jazz'),
        ('Classical', 'Classical'),
        ('Dance', 'Dance'),
        ('Acoustic', 'Acoustic')
    )
    Audio = models.CharField(max_length=255)
    Artist = models.CharField(max_length=255)
    Audiofile = models.FileField(blank=True, null=True)
    Imageurl = models.FileField(blank=True, null=True)
    Genre = models.CharField(max_length=100, choices=OPTIONS)
    Time = models.CharField(max_length=60)
    color = models.CharField(max_length=60, null=True)


class Playlist(models.Model):
    Playlistname = models.CharField(max_length=255)
    Songs = models.JSONField(models.CharField(max_length=255))
    User = models.IntegerField(null=True)

Music/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from django.forms.fields import CharField
from django.http import request
from django.views.decorators.csrf import csrf_protect


from Music.views import User
from .models import Song, User, Playlist

passwordInputWidget = {"Password": forms.PasswordInput()}


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = "__all__"
        widgets = [passwordInputWidget]


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["Username", "Password"]
        widgets = [passwordInputWidget]


song = Song.objects.all()
choice_f = []
for x in song:
    choice_f.append((x.id, x.Audio))


Songswidget = {"Songs": forms.CheckboxSelectMultiple(choices=choice_f)}


class PlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ["Playlistname", "Songs", "User"]
        widgets = [Songswidget]

    Playlistname = forms.CharField()
    Songs = forms.MultipleChoiceField(
        choices=choice_f, widget=forms.CheckboxSelectMultiple
    )
    User = forms.IntegerField()

Music/views.py
from django.forms.forms import Form
from django.http.response import JsonResponse
from django.shortcuts import render, redirect

# imported our models
from .models import Song, User, Playlist
from .forms import RegisterForm, LoginForm, PlaylistForm
from rest_framework.decorators import api_view
from .decorators import user_login_required


import os
import sklearn
import numpy as np
import pandas as pd
import joblib as joblib
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from pandas import read_csv
import numpy as np
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import joblib as joblib
from joblib import dump, load
import argparse
import os
import matplotlib.pyplot as plt
import io
import urllib
import base64


@user_login_required
def index(request):
    user = get_user(request)
    songs = Song.objects.all()
    playlists = Playlist.objects.filter(User=request.session["user_id"])
    context = {"songs": songs, "user": user, "playlist": playlists}
    return render(request, "index.html", context)


def register(request):
    form = RegisterForm()
    success = None
    if request.method == "POST":
        if User.objects.filter(Username=request.POST["Username"]).exists():
            error = "This username is already taken"
            return render(request, "register.html", {"form": form, "error": error})
        if User.objects.filter(Email=request.POST["Email"]).exists():
            error = "This email is already taken"
            return render(request, "register.html", {"form": form, "error": error})
        form = RegisterForm(request.POST)
        new_user = form.save(commit=False)
        new_user.save()
        success = "New User Created Successfully !"
    return render(request, "register.html", {"form": form, "success": success})


def login(request):
    form = LoginForm()
    if request.method == "POST":
        Username = request.POST["Username"]
        Password = request.POST["Password"]
        if User.objects.filter(Username=Username, Password=Password).exists():
            user = User.objects.get(Username=Username)
            request.session["user_id"] = user.id
            Userage = User.objects.get(id=request.session["user_id"])
            age = Userage.Age
            gender = Userage.Gender

            gender = gender.lower()

            if gender == "male":
                gender = 1
            else:
                gender = 0

            model = os.path.join(
                "C:/Users/harman/Documents/GitHub/musicplayer/JupyterNotebook",
                "forest.pkl",
            )
            model = joblib.load(model)
            data = [age, gender]
            x = np.array(data).reshape(1, -1)

            x = np.array(x, dtype=np.int64)

            results = model.predict(x)
            if results[0] == 0:
                results = "HipHop"
            elif results[0] == 1:
                results = "Jazz"
            elif results[0] == 2:
                results = "Classical"
            elif results[0] == 3:
                results = "Dance"
            elif results[0] == 4:
                results = "Acoustic"
            request.session["RGenre"] = results
            return redirect("Music:index")
    return render(request, "login.html", {"form": form})


@user_login_required
def recommended_song(request):
    Songs = Song.objects.filter(Genre=request.session["RGenre"])
    user = get_user(request)
    playlists = Playlist.objects.filter(User=request.session["user_id"])
    context = {"user": user, "songs": Songs, "playlist": playlists}
    return render(request, "recommendedsongs.html", context)


def get_user(request):
    return User.objects.get(id=request.session["user_id"])


@user_login_required
def playlist_view(request):
    context = {}
    form = PlaylistForm(request.POST)
    user = get_user(request)
    playlists = Playlist.objects.filter(User=request.session["user_id"])
    context = {"form": form, "user": user, "playlist": playlists}
    if request.method == "POST":
        if form.is_valid():
            form = PlaylistForm(request.POST)
            new_playlist = form.save(commit=False)
            new_playlist.save()
        else:
            print("not working")
    return render(request, "createplaylist.html", context)


@user_login_required
@api_view(["GET"])
def playlist_detail(request, id):

    if request.method == "GET":
        singleplaylist = Playlist.objects.get(id=id)
        Playlistsongs = []
        for x in singleplaylist.Songs:
            Playlistsongs.append(Song.objects.get(id=x))
        user = get_user(request)
        songs = Playlistsongs
        playlists = Playlist.objects.filter(User=request.session["user_id"])
        context = {
            "singleplaylist": singleplaylist,
            "user": user,
            "songs": songs,
            "playlist": playlists,
        }

    return render(request, "singleplaylist.html", context)


def logout(request):
    if "user_id" in request.session:
        del request.session["user_id"]
    return redirect("Music:login")

Music/templates/createplaylist.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body></body>
</html>
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>My Music Player</title>
    <link href="{% static './style.css' %}" rel="stylesheet" />
  </head>
  <body>
    <!-- partial:index.partial.html -->
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Flat music player</title>
      </head>
      <body>
        <div class="sidenav">
          <img
            src="https://www.pngall.com/wp-content/uploads/5/User-Profile-PNG.png"
            alt=""
            style="height: 120px; width: 120px; padding: 0px 30px"
          />

          <h2>Welcome {{ user.Username }}</h2>

          <p>Email : {{ user.Email }}</p>
          <a style="color: black" href="{% url 'Music:index' %}">Home</a>

          <a style="color: black" href="{% url 'Music:playlist' %}"
            >Create Playlist</a
          >
          {% for item in playlist %}
          <a
            style="color: black"
            href="{% url 'Music:singleplaylist' id=item.id %}"
            >{{item.Playlistname}}</a
          >

          {% endfor %}
          <div>
            To logout,
            <a style="color: black" href="{% url 'Music:logout' %}"
              >Click Here</a
            >
          </div>
        </div>
        <div class="main" style="padding: 0px 80px">
          <form method="POST" class="form-group">
            {% csrf_token %}
            <div class="form-group">
              <label>Playlist Name </label><br />
              {{ form.Playlistname }}<br />
            </div>
            <div class="form-group">
              <label>User ID </label><br />
              {{ form.User }}<br />
            </div>
            <br />
            <div class="form-group">
              <label>Select Song</label>
              {{form.Songs}}
            </div>

            <button type="submit" class="btn btn-primary">
              Create Playlist
            </button>
          </form>
        </div>
      </body>
    </html>
    <!-- partial -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelement-and-player.min.js"></script>
  </body>
</html>

Music/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Music Player</title>
    <link href="{% static './style.css' %}" rel="stylesheet" />
  </head>
  <body>
    <!-- partial:index.partial.html -->
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Music player</title>
      </head>
      <body>
        <div class="sidenav">
          <img
            src="https://www.pngall.com/wp-content/uploads/5/User-Profile-PNG.png"
            alt=""
            style="height: 120px; width: 120px; padding: 0px 30px"
          />

          <h2>Welcome {{ user.Username }}</h2>

          <p>Email : {{ user.Email }}</p>
          <a style="color: black" href="{% url 'Music:index' %}">Home</a>
          <a style="color: black" href="{% url 'Music:playlist' %}"
            >Create Playlist</a
          >
          {% for item in playlist %}
          <a
            style="color: black"
            href="{% url 'Music:singleplaylist' id=item.id %}"
            >{{item.Playlistname}}</a
          >
          {% endfor %}
          <a style="color: black" href="{% url 'Music:recommendedsong' %}"
            >Recommended Songs</a
          >

          <div>
            To logout,
            <a style="color: black" href="{% url 'Music:logout' %}"
              >Click Here</a
            >
          </div>
        </div>
        <div class="main">
          {% for item in songs %}
          <div
            class="card"
            style="float: left; margin-left:110px; margin-top: 50px; background-color:{{item.color}}"
          >
            <br />
            <br />
            <img
              src="{{item.Imageurl.url}}"
              alt="Avatar"
              style="width: 100%; height: 300px; border-radius: 100px"
            />
            <audio controls>
              <source src="{{item.Audiofile.url}}" type="audio/mp3" />
            </audio>
            <div class="container">
              <h5><b>{{item.Audio}}</b></h5>
              <h6>{{item.Artist}}</h6>
            </div>
          </div>
          {% endfor %}
        </div>
      </body>
    </html>
    <!-- partial -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelement-and-player.min.js"></script>
  </body>
</html>

Music/templates/login.html
   <!DOCTYPE html>
   <html lang="en">
   <head>
       <meta charset="UTF-8">
       <meta http-equiv="X-UA-Compatible" content="IE=edge">
       <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <title>Document</title>
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    </head>
   <body>
    
       <div class="main" style="padding: 0px 80px">
        <form method="POST" class="form-group">
          {% csrf_token %}
             <label>User Name </label><br>
            {{ form.Username }}<br>
             <label>Password </label><br>
            {{ form.Password }}<br><br>
           <button type="submit" class="btn btn-primary">
            Login  
          </button>
        </form>
        <div>Don't have an account? <a href="{% url 'Music:register' %}">Sign up</a>

      </div>
   </body>
   </html>

Music/templates/recommendedsongs.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Music Player</title>
    <link href="{% static './style.css' %}" rel="stylesheet" />
  </head>
  <body>
    <!-- partial:index.partial.html -->
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Music player</title>
      </head>
      <body>
        <div class="sidenav">
          <img
            src="https://www.pngall.com/wp-content/uploads/5/User-Profile-PNG.png"
            alt=""
            style="height: 120px; width: 120px; padding: 0px 30px"
          />

          <h2>Welcome {{ user.Username }}</h2>

          <p>Email : {{ user.Email }}</p>
          <a style="color: black" href="{% url 'Music:index' %}">Home</a>
          <a style="color: black" href="{% url 'Music:playlist' %}"
            >Create Playlist</a
          >
          {% for item in playlist %}
          <a
            style="color: black"
            href="{% url 'Music:singleplaylist' id=item.id %}"
            >{{item.Playlistname}}</a
          >
          {% endfor %}

          <div>
            To logout,
            <a style="color: black" href="{% url 'Music:logout' %}"
              >Click Here</a
            >
          </div>
        </div>
        <div class="main">
          {% for item in songs %}
          <div
            class="card"
            style="float: left; margin-left:110px; margin-top: 50px; background-color:{{item.color}}"
          >
            <br />
            <br />
            <img
              src="{{item.Imageurl.url}}"
              alt="Avatar"
              style="width: 100%; height: 300px; border-radius: 100px"
            />
            <audio controls>
              <source src="{{item.Audiofile.url}}" type="audio/mp3" />
            </audio>
            <div class="container">
              <h5><b>{{item.Audio}}</b></h5>
              <h6>{{item.Artist}}</h6>
            </div>
          </div>
          {% endfor %}
        </div>
      </body>
    </html>
    <!-- partial -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelement-and-player.min.js"></script>
  </body>
</html>

Music/templates/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Document</title>
  </head>
  <body>
    {% if success %}
    <div>{{ success }}</div>
    {% endif %} {% if error %}
    <div>{{ error }}</div>
    {% endif %}
    <div class="main" style="padding: 0px 80px">

    <form method="POST" class="form-group">
      {% csrf_token %}
      <label>First Name </label><br />
      {{ form.Firstname }}<br />
      <label>Last Name </label><br />
      {{ form.LastName }}<br />
      <label>User Name </label><br />
      {{ form.Username }}<br />
      <label>Email </label><br />
      {{ form.Email }}<br />
      <label>Password </label><br />
      {{ form.Password }}<br />
      <label>Gender </label><br />
      {{ form.Gender }}<br />
      <label>Age </label><br />
      {{ form.Age }}<br /><br />
      <button type="submit" class="btn btn-primary">Register</button>
    </form>
    <div>Login if you have a account? <a href="{% url 'Music:login' %}">Sign up</a>
    </div>
  </body>
</html>

Music/templates/singleplaylist.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Music Player</title>
    <link href="{% static './style.css' %}" rel="stylesheet" />
  </head>
  <body>
    <!-- partial:index.partial.html -->
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Music player</title>
      </head>
      <body>
        <div class="sidenav">
          <img
            src="https://www.pngall.com/wp-content/uploads/5/User-Profile-PNG.png"
            alt=""
            style="height: 120px; width: 120px; padding: 0px 30px"
          />

          <h2>Welcome {{ user.Username }}</h2>

          <p>Email : {{ user.Email }}</p>
          <a style="color: black" href="{% url 'Music:index' %}">Home</a>

          <a style="color: black" href="{% url 'Music:playlist' %}"
            >Create Playlist</a
          >
          {% for item in playlist %}

          <a
            style="color: black"
            href="{% url 'Music:singleplaylist' id=item.id %}"
            >{{item.Playlistname}}</a
          >

          {% endfor %}
          <div>
            To logout, <a href="{% url 'Music:logout' %}">Click Here</a>
          </div>
        </div>
        <div class="main">
          <h1 style="padding: 0px 60px">{{singleplaylist.Playlistname}}</h1>

          {% for item in songs %}
          <div
            class="card"
            style="float: left; margin-left:110px; margin-top: 50px; background-color:{{item.color}}"
          >
            <br />
            <br />
            <img
              src="{{item.Imageurl.url}}"
              alt="Avatar"
              style="width: 100%; height: 300px; border-radius: 100px"
            />
            <audio controls>
              <source src="{{item.Audiofile.url}}" type="audio/mp3" />
            </audio>
            <div class="container">
              <h5><b>{{item.Audio}}</b></h5>
              <h6>{{item.Artist}}</h6>
            </div>
          </div>
          {% endfor %}
        </div>
      </body>
    </html>
    <!-- partial -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelement-and-player.min.js"></script>
  </body>
</html>